// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///import 'firebase_options.dart';
/// // ...
///await Firebase.initializeApp(
///options: DefaultFirebaseOptions.currentPlatform,
///);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxbwTg9LimiLUWQFL1MVtOwbxAvvShaXc',
    appId: '1:898304059646:web:b4bd3c99f1d8c86c355daf',
    messagingSenderId: '898304059646',
    projectId: 'nusafoodcek',
    authDomain: 'nusafoodcek.firebaseapp.com',
    storageBucket: 'nusafoodcek.appspot.com',
    measurementId: 'G-WEXXMNJ8GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIZRaimmNIw85Waq7THQBTlyJrrBgqwBA',
    appId: '1:898304059646:android:a28fc72a4112bf9c355daf',
    messagingSenderId: '898304059646',
    projectId: 'nusafoodcek',
    storageBucket: 'nusafoodcek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkOa08U5RyJQgVZ3IErNn3NDTgD7SpQyg',
    appId: '1:898304059646:ios:af6a3758dad43fa0355daf',
    messagingSenderId: '898304059646',
    projectId: 'nusafoodcek',
    storageBucket: 'nusafoodcek.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkOa08U5RyJQgVZ3IErNn3NDTgD7SpQyg',
    appId: '1:898304059646:ios:af6a3758dad43fa0355daf',
    messagingSenderId: '898304059646',
    projectId: 'nusafoodcek',
    storageBucket: 'nusafoodcek.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxbwTg9LimiLUWQFL1MVtOwbxAvvShaXc',
    appId: '1:898304059646:web:c6c1880cb1ad2b51355daf',
    messagingSenderId: '898304059646',
    projectId: 'nusafoodcek',
    authDomain: 'nusafoodcek.firebaseapp.com',
    storageBucket: 'nusafoodcek.appspot.com',
    measurementId: 'G-RZTBS5Y49Z',
  );
}
